### ISSUE TITLE
How to transform the Connector to odoo10?

### ISSUE THREAD

**Issue by oceandhy** [gibso/Shopware-Odoo-Connector#1]
Hi,How to transform the Connector to odoo10?
I run this Connector in odoo10,but it doesn't work...
Could you tell me how to transform?  Thanks!

**Comment by gibso** [comment]
Hey oceandhy,
the shopware connector implements the [Connector Framework](https://github.com/OCA/connector) and was migrated from the [Magento Connector](https://github.com/OCA/connector-magento). The community is migrating both projects to Odoo 10 at the moment, but the migration is not finished yet. You can look out for updates in these two issues: [Roadmap v10 #206](https://github.com/OCA/connector/issues/206) and [Migration to version 10.0 #238](https://github.com/OCA/connector-magento/issues/238)
Have a nice day, Oliver.

**Comment by jaredkipe** [comment]
I believe this can be closed now.
