### ISSUE TITLE
How long did you developing this Connector?

### ISSUE THREAD

**Issue by oceandhy** [gibso/Shopware-Odoo-Connector#2]
Could you tell me how lang did it take to develop this program?Thank you!

**Comment by gibso** [comment]
Hey oceandhy,
I developed this connector within the scope of my bachelor thesis. The development took about 2.5 months. But i had no prior knowledge in python and the odoo system.
Greetings, Oliver.

**Comment by oceandhy** [comment]
You are great!What will be happened when we don't use shopware-PHP-connector?

**Comment by gibso** [comment]
Thanks a lot 👍 I hoped to contribute something to the open source community with this project ;-)
What do you mean with "shopware-PHP-connector"?

**Comment by gibso** [comment]
For the future I should translate the documentation into english i guess.

**Comment by OSevangelist** [comment]
Hi @oceandhy and @gibso let me step in here as well. Since i was the mentor of @gibso scientific work we @initos-com plan to take the that whole thing further complete it at migrate it to version 10+ of Odoo. @oceandhy what is your thoughts would you be interested in contributing as well ?

**Comment by oceandhy** [comment]
@OSevangelist I really want to get involved in the project, but my python and odoo foundation are very poor, but I'm starting to do it now.I am willing to contribute my code.

**Comment by oceandhy** [comment]
@gibso Hi,Why am I always wrong when I synchronize shopware data with odoo8? Is it normal for your program test?

**Comment by gibso** [comment]
@oceandhy I don't fully understand your problem. Are you talking about the existing unit tests? I just adopted them and did not really check for their correctness.

**Comment by oceandhy** [comment]
@gibso Did you use shopware's account for the test? Can the program run smoothly?There was a lot of bugs when I synchronize the data from shopware.

**Comment by gibso** [comment]
In fact, the connector is only partially migrated. There are some features still missing in the Connector, e.g. the import of Orders. The icluded features that are implemented and running are listed in the [Readme](https://github.com/gibso/Shopware-Odoo-Connector/blob/master/README.md) (unfortunately in german). 

Currently supported features are:
- import of Metadata (Shopware Shops)
- import of articlecategories
- import of articles with variants
- export of stock quantity of existing variants

Currently **not** supported features:
- import of customerdata
- import of customergroups
- import of article images
- import of orderdata
- export of delivery status of existing orders 

The supported Features have been tested with an shopware account. I hope these information can help you.

**Comment by oceandhy** [comment]
Thank you very much!
